# Generated by Django 5.2.2 on 2025-06-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctormapping',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
